name: ukbrest
channels:
  - defaults
dependencies:
  - coverage
  - flask-httpauth=3.2
  - eventlet=0.21.0
  - ruamel.yaml=0.15.34
  - sqlalchemy
  - flask
  - gevent=1.2.2
  - sqlite=3.20.1
  - coveralls=1.2.0
  - python=3.6.3
  - psycopg2=2.7.3.2
  - lxml=4.1.1
  - html5lib=0.999999999
  - gunicorn=19.7.1
  - joblib=0.11
  - nose=1.3.7
  - numpy=1.13.3
  - ipython=6.2.1
  - beautifulsoup4=4.6.0
  - flask-restful=0.3.6
  - pandas=0.21.0

